import { useMemo, useState } from "react";
import ReactModal from "react-modal";

interface PromptModalProps {
    close(): void,
}
const prompt = `
You are generating code for a custom C-like scripting language.

STRICT RULES:
- only listed functions and modules exist!
- do not assume undocumented behavior, do not invent new modules or functions!
- if the task cannot be implemented with the provided API, respond exactly: "This cannot be implemented with the given API. \n\*\*Reason:\*\*<reason>"
- #include is replaced with "import module;"
- there is no address manipulation or pointers
- string counts as a primitive type
- structs, generic types do not exist
- code can not exist outside of functions
- main() function is entry point

Available API in format: module.function(parameter_types)->return_type;description
- bot.get_block(string direction)->string; gets block type in direction relative to the bot
- bot.mine(string direction)->int; mines block in the direction relative to the bot. does not move the bot. returns 1 when done
- bot.move(string direction)->int; moves bot in specified direction. returns 1 if success, otherwise 0
- bot.chat(string message)->int; prints message in chat, returns 1

Some parameters require specific values:
direction: forward, up, down, left, right

Task:
`.trim();
export default function PromptModal({ close }: PromptModalProps) {
    const [ isCopied, setIsCopied ] = useState(false);
    const handleCopy = useMemo(() => () => {
        navigator.clipboard.writeText(prompt);
        setIsCopied(true);
    }, []);
    return <ReactModal isOpen={true} className="ai-prompt" overlayClassName="ai-prompt-overlay" onRequestClose={close}>
        <h3>AI Prompt</h3>
        This prompt is written to improve the code generated by AI. Copy the text from below and paste it to the GPT you use before asking it for help.
        <pre onClick={handleCopy} data-copied={isCopied.toString()}>{prompt}</pre>
        <small>{isCopied && "Prompt is now copied to your clipboard!"}</small>
    </ReactModal>
}